### ISSUE TITLE
Adjust the splash page

### ISSUE THREAD

**Issue by rbatzing** [rbatzing/musicfindercnx#1]
Text and Bootstrap updates

**Comment by rbatzing** [comment]
## Tasks
- [ ] Establish GitHub space
- [x] Establish a Heroku webspace
- [x] Link the GitHub to Heroku
- [x] Select a free simple BootStrap template 
- [x] Adjust the BootStrap Slash page
- [x] Create a project icon
