### ISSUE TITLE
Develop music search page

### ISSUE THREAD

**Issue by rbatzing** [rbatzing/musicfindercnx#2]
List of moods  and genre tags for drop down

**Comment by rbatzing** [comment]
## Task list
- [x] A graphic of a range of emotions . 
- [x] An image map for the emoticons to identify which emotion the user selects
- [x] A javascript function is needed to adjust the image map according any responsive rescaling.
- [ ] Add a JavaScript routine to support and search the JSON lyric list
- [ ] Create a standard set of genres
- [ ] Create a standard set of moods/emotions to be supported
