### ISSUE TITLE
Upload sample music with tags to soundcloud

### ISSUE THREAD

**Issue by rbatzing** [rbatzing/musicfindercnx#3]
Create a basic test set of music

**Comment by rbatzing** [comment]
## Task List
- [ ] Create a play list with 30 songs within SoundCloud
- [ ] Tag the entries by Genre
- [ ] Tag the entries by empathetic appeal
