### ISSUE TITLE
Interface between the search form and soundcloud api

### ISSUE THREAD

**Issue by rbatzing** [rbatzing/musicfindercnx#4]
## Task List
- [x] Apply for a SoundCloud API (but the key will be 2 weeks in coming).

- [ ] Add the SoundCloud API

- [ ] Link to the SoundCloud API search

- [ ] Add JavaScript to parse the JSON search results
