### ISSUE TITLE
Create lyrics textbase

### ISSUE THREAD

**Issue by rbatzing** [rbatzing/musicfindercnx#5]
## Task list
- [x] Obtain a collection of lyrics for Christian hymns and songs from Bruce Rowe
- [x] Convert the Access DB into JSON
- [ ] Create the JavaScript interface to identify text
- [ ] Look at some means for categorizing the content of a song (a vector of Roget's thesaurus numbers??)

**Comment by ttarczy** [comment]
Good evening! My name is Trina.  Not sure if you are still at it, but we are in Sacramento working on the Music Finder as well.  How did you convert your Access db into JSON?  We are trying to figure out how to not utilize the Access DB we started with.
